# Generated by Django 5.1.7 on 2025-05-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_quiz_difficulty_quiz_language_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('fill_in_blank', 'Fill in the Blank'), ('matching', 'Matching'), ('mixed', 'Mixed')], default='multiple_choice', max_length=20),
        ),
    ]
