# Generated by Django 5.1.7 on 2025-05-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
