# Generated by Django 5.2.1 on 2025-06-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pdfdocument_user'),
        ('api', 'cleanup_pdfs'),
    ]

    operations = [
    ]
