# Generated by Django 5.2.1 on 2025-06-05 07:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_pdfdocument_user_delete_youtubecontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='QuizModel',
        ),
    ]
